;; https://abc044.contest.atcoder.jp/tasks/arc060_a
(let* ((n (read))
       (a (read))
       (x (make-array n :initial-contents (loop :repeat n :collect (read))))
       (cache (make-array (expt 51 4) :initial-element nil)))
  (defun s (v k i)
    (cond ((= i n) (if (and (> v 0) (= v (* k a))) 1 0))
          ((> v (* a n)) 0)
          (t (let ((key (+ (* v 51 51) (* k 51) i)))
               (if (aref cache key)
                   (aref cache key)
                   (setf (aref cache key) (+ (s v k (1+ i))
                                             (s (+ v (aref x i)) (1+ k) (1+ i)))))))))
  (format t "~a~%" (s 0 0 0)))
