# This file was *autogenerated* from the file 8.sage
from sage.all_cmdline import *   # import sage library

_sage_const_1 = Integer(1)#!/usr/bin/sage
for c in range(input()):
    m, r = [], []
    for i in range(input()):
        p, t = map(int, raw_input().split())
        m.append((p - t - i) % p)
        r.append(p)
    try:
        r = crt(m, r)
    except:
        r = 'NEVER'
    print('Case #{}: {}'.format(c + _sage_const_1 , r))

